GET http://localhost:5005/library/16

###

POST http://localhost:5005/library
Content-Type: application/json

{
  "Name": "goonmsy",
  "Genre": "pornhub",
  "Price": 74,
  "ReleaseDate": "2023-11-06"
}

###

PUT http://localhost:5005/library/15
Content-Type: application/json

{
  "Name": "goonmsy",
  "Genre": "pornhub",
  "Price": 74,
  "ReleaseDate": "2023-11-06"
}

###

DELETE http://localhost:5005/library/1